services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "default_port_1:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=example_password
    volumes:
      - ./nextcloud:/var/www/html
    restart: unless-stopped
    networks:
      - nextcloud

networks:
  nextcloud:
    driver: bridge
