services:
  stirling-pdf:
    image: frooodle/s-pdf
    container_name: s-pdf
    ports:
      - "default_port_1:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=false
    volumes:
      - ./data:/usr/share/tesseract-ocr/5/tessdata
      - ./config:/configs
      - ./logs:/logs
    restart: unless-stopped
    networks:
      - s-pdf

networks:
  s-pdf:
    driver: bridge