services:
  searxng:
    image: alandoyle/searxng
    container_name: searxng
    init: true
    ports:
      - "default_port_1:8080"
    volumes:
      - ./config:/etc/searxng
      - ./templates:/usr/local/searxng/searx/templates/simple
      - ./theme:/usr/local/searxng/searx/static/themes/simple
    restart: unless-stopped
    networks:
      - searxng

networks:
  searxng:
    driver: bridge