services:
  uptimekuma:
    image: louislam/uptime-kuma
    container_name: uptimekuma
    ports:
      - "default_port_1:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - uptimekuma

networks:
  uptimekuma:
    driver: bridge