services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/var/www/html
      - ./nginx/log:/var/log/nginx
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    networks:
      - web

networks:
  web:
    driver: bridge