services:
  openresty:
    image: openresty/openresty:1.25.3.2-0-alpine
    container_name: openresty
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./html:/var/www/html
      - ./log:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=512m
    networks:
      - openresty

networks:
  openresty:
    driver: bridge