services:
  serverstatus:
    image: cppla/serverstatus
    container_name: serverstatus
    restart: unless-stopped
    ports:
      - '35601:35601'
      - '8080:80'
    volumes:
      - './serverstatus-monthtraffic:/usr/share/nginx/html/json'
      - './serverstatus-config.json:/ServerStatus/server/config.json'
    networks:
      - serverstatus

networks:
  serverstatus:
    driver: bridge
