services:
  sub-store:
    image: xream/sub-store
    container_name: sub-store
    restart: unless-stopped
    environment:
      - SUB_STORE_CRON=50 23 * * *
      - SUB_STORE_FRONTEND_BACKEND_PATH=/example_password
    ports:
      - "default_port_1:3001"
    volumes:
      - ./data:/opt/app/data
    networks:
      - sub-store

networks:
  sub-store:
    driver: bridge
